# Generated by Django 4.0.5 on 2022-08-06 14:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task2question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default='without any category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ielts.category')),
            ],
        ),
        migrations.CreateModel(
            name='writingtask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(default='coding', on_delete=django.db.models.deletion.CASCADE, to='ielts.task2question')),
            ],
        ),
        migrations.CreateModel(
            name='writingtask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(default='without any category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ielts.categorytask1')),
            ],
        ),
    ]
