# Generated by Django 4.1 on 2022-08-27 12:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPartOneTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPartThreeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task2question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default='without any category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ielts.categorytask2')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTaskTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(default='coding', on_delete=django.db.models.deletion.CASCADE, to='ielts.task2question')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTaskOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ielts.categorytask1')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPartThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=255)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(blank=True, max_length=255)),
                ('answer2', models.TextField(blank=True)),
                ('question3', models.CharField(blank=True, max_length=255)),
                ('answer3', models.TextField(blank=True)),
                ('question4', models.CharField(blank=True, max_length=255)),
                ('answer4', models.TextField(blank=True)),
                ('question5', models.CharField(blank=True, max_length=255)),
                ('answer5', models.TextField(blank=True)),
                ('question6', models.CharField(blank=True, max_length=255)),
                ('answer6', models.TextField(blank=True)),
                ('question7', models.CharField(blank=True, max_length=255)),
                ('answer7', models.TextField(blank=True)),
                ('question8', models.CharField(blank=True, max_length=255)),
                ('answer8', models.TextField(blank=True)),
                ('topic', models.ForeignKey(default='unnamed', on_delete=django.db.models.deletion.CASCADE, to='ielts.speakingpartthreetopic')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPartOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('topic', models.ForeignKey(default='unnamed', on_delete=django.db.models.deletion.CASCADE, to='ielts.speakingpartonetopic')),
            ],
        ),
    ]
