# Generated by Django 4.1 on 2022-08-25 05:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
