# Generated by Django 4.0.5 on 2022-08-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtask1',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ielts.categorytask1'),
        ),
    ]
