# Generated by Django 4.1 on 2022-09-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_remove_speakingpartthree_answer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(choices=[('noun', 'noun'), ('determiner', 'determiner'), ('pronoun', 'pronoun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('preposition', 'preposition'), ('conjunction', 'conjunction')], default='noun', max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
    ]
