# Generated by Django 4.1 on 2022-09-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='level',
            field=models.CharField(choices=[('general', 'general'), ('academic', 'academic')], default='general', max_length=100),
        ),
    ]
